# Generated by Django 5.2.10 on 2026-01-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('bio', models.TextField(blank=True, verbose_name='História')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
