# Generated by Django 5.2.10 on 2026-01-07 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supporter',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='supporter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supporter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supporters/logos/'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
