"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

import os
from pathlib import Path

import dj_database_url

# ----------------------------------------------------
# BASE
# ----------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Render: coloque SECRET_KEY no Environment
SECRET_KEY = os.getenv("SECRET_KEY", "dev-insecure-secret-key")

# Render: DEBUG=0 (False)
# Local default: DEBUG=1
DEBUG = os.getenv("DEBUG", "1") == "1"

# Hosts (no Render coloque seu domínio/URL, ou deixe "*" enquanto testa)
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://*.ngrok-free.app",
    "https://*.ngrok.io",
]

# ----------------------------------------------------
# APPLICATIONS
# ----------------------------------------------------
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    # Apps
    "core",
    "members",
    "catches",
    "supporters",
    "weather",
]

# ----------------------------------------------------
# MIDDLEWARE
# ----------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# ----------------------------------------------------
# TEMPLATES
# ----------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ----------------------------------------------------
# DATABASE
# ----------------------------------------------------
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
  "default": {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": "nabosystem",
    "USER": "nabosystem_user.",
    "PASSWORD": "blZ423LQgNjb61QWGqomar5LRBVgyA3C",
    "HOST": "dpg-d5jv4evpm1nc73cb96n0-a",
    "PORT": "5432",
  }
}
else:
    # Local SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ----------------------------------------------------
# PASSWORD VALIDATION
# ----------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ----------------------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------------------
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

# ----------------------------------------------------
# STATIC / MEDIA
# ----------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))

# Permite servir media via Django quando necessário (ex: ambiente sem proxy)
SERVE_MEDIA = os.getenv("SERVE_MEDIA", "0") == "1"

# ----------------------------------------------------
# DEFAULT PRIMARY KEY
# ----------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ----------------------------------------------------
# LOGIN / LOGOUT
# ----------------------------------------------------
LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/auth/me/"
LOGIN_URL = "/auth/login/"

# ----------------------------------------------------
# JAZZMIN
# ----------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Nabos Admin",
    "site_header": "NabosSystem",
    "site_brand": "Equipe Nabos",
    "site_logo_classes": "none",
    "welcome_sign": "Bem-vinda(o) ao admin da Equipe Nabos",
    "copyright": "Equipe Nabos",
    "topmenu_links": [
        {"name": "Site", "url": "/", "new_window": True},
        {"name": "Ranking", "url": "/ranking/", "new_window": True},
        {"name": "Grupo", "url": "/grupo/", "new_window": True},
        {"model": "auth.User"},
    ],
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",

        "members": "fas fa-id-card",
        "members.member": "fas fa-user-friends",

        "catches": "fas fa-fish",
        "catches.catch": "fas fa-fish-fins",
        "catches.species": "fas fa-list",

        "supporters": "fas fa-handshake",
        "supporters.supporter": "fas fa-hand-holding-heart",

        "core": "fas fa-layer-group",
        "weather": "fas fa-cloud-sun-rain",
    },
    "custom_links": {
        "members": [
            {
                "name": "Ir para página do Grupo",
                "url": "/grupo/",
                "icon": "fas fa-external-link-alt",
                "permissions": ["members.view_member"],
            }
        ],
        "catches": [
            {
                "name": "Registrar captura (front)",
                "url": "/catches/new/",
                "icon": "fas fa-plus",
            }
        ],
    },
    "order_with_respect_to": ["members", "catches", "weather", "supporters", "auth"],
    "custom_app_menu": [
        {
            "app": "members",
            "label": "Cadastros",
            "icon": "fas fa-id-card",
            "models": [
                {"name": "members.Member", "label": "Membros"},
                {"name": "auth.User", "label": "Usuários"},
                {"name": "auth.Group", "label": "Grupos"},
            ],
        },
        {
            "app": "catches",
            "label": "Pesca",
            "icon": "fas fa-fish",
            "models": [
                {"name": "catches.Catch", "label": "Capturas"},
                {"name": "catches.Species", "label": "Espécies"},
            ],
        },
        {
            "app": "weather",
            "label": "Tempo",
            "icon": "fas fa-cloud-sun-rain",
            "models": [
                {"name": "weather.Spot", "label": "Spots"},
                {"name": "weather.ForecastHour", "label": "Previsões (horas)"},
                {"name": "weather.StormglassRequestLog", "label": "Logs Stormglass"},
            ],
        },
        {
            "app": "supporters",
            "label": "Apoiadores",
            "icon": "fas fa-handshake",
            "models": [{"name": "supporters.Supporter", "label": "Apoiadores"}],
        },
    ],
    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "collapsible",
    },
    "language_chooser": False,
}

# ----------------------------------------------------
# SECURITY (Render)
# ----------------------------------------------------
if not DEBUG:
    # Render usa proxy / https
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "1") == "1"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
