"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-izoewyftpdts_7hpw7=rlwg&uj%$0adldqg78_ng6+f4hb9(0*'
DEBUG = True

ALLOWED_HOSTS = ["*"]  # depois você restringe
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok.io",
    "https://*.ngrok-free.app",
]

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "import_export",
    # Apps instalados
    "core",
    "members",
    "catches",
    "supporters",
    "weather",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.media",
            ],
        },
    },
]

JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "Nabos Admin",
    "site_header": "NabosSystem",
    "site_brand": "Equipe Nabos",
    # "site_logo": "media/assets/logo/logo_nabos.png",  # usa STATIC; se estiver no media, melhor mover pro static
    # "login_logo": "media/assets/logo/logo_nabos.png",
    "site_logo_classes": "none",
    "welcome_sign": "Bem-vinda(o) ao admin da Equipe Nabos",
    "copyright": "Equipe Nabos",

    # Top menu links
    "topmenu_links": [
        {"name": "Site", "url": "/", "new_window": True},
        {"name": "Ranking", "url": "/ranking/", "new_window": True},
        {"name": "Grupo", "url": "/grupo/", "new_window": True},
        {"model": "auth.User"},
    ],

    # User avatar (se quiser mostrar na navbar)
    "user_avatar": None,

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Icons (FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",

        "members": "fas fa-id-card",
        "members.member": "fas fa-user-friends",

        "catches": "fas fa-fish",
        "catches.catch": "fas fa-fish-fins",
        "catches.species": "fas fa-list",

        "supporters": "fas fa-handshake",
        "supporters.supporter": "fas fa-hand-holding-heart",

        "core": "fas fa-layer-group",
    },

    # Custom links/groups in sidebar
    "custom_links": {
        "members": [
            {
                "name": "Ir para página do Grupo",
                "url": "/grupo/",
                "icon": "fas fa-external-link-alt",
                "permissions": ["members.view_member"],
            }
        ],
        "catches": [
            {
                "name": "Registrar captura (front)",
                "url": "/catches/new/",
                "icon": "fas fa-plus",
            }
        ],
    },

    # Order + grouping sidebar apps
    "order_with_respect_to": [
        "members",
        "catches",
        "supporters",
        "auth",
    ],

    # Sidebar menu structure
    "custom_app_menu": [
        {
            "app": "members",
            "label": "Cadastros",
            "icon": "fas fa-id-card",
            "models": [
                {"name": "members.Member", "label": "Membros"},
                {"name": "auth.User", "label": "Usuários"},
                {"name": "auth.Group", "label": "Grupos"},
            ],
        },
        {
            "app": "catches",
            "label": "Pesca",
            "icon": "fas fa-fish",
            "models": [
                {"name": "catches.Catch", "label": "Capturas"},
                {"name": "catches.Species", "label": "Espécies"},
            ],
        },
        {
            "app": "supporters",
            "label": "Apoiadores",
            "icon": "fas fa-handshake",
            "models": [
                {"name": "supporters.Supporter", "label": "Apoiadores"},
            ],
        },
    ],

    # UI tweaks
    "related_modal_active": True,
    "use_google_fonts_cdn": True,

    # Change view
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "collapsible",
    },

    # language
    "language_chooser": False,
}


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR/'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=True,  # Render usa TLS no Postgres
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGOUT_REDIRECT_URL = "/"          # volta pro site (home)
LOGIN_REDIRECT_URL = "/auth/me/"   # depois do login vai pro perfil
LOGIN_URL = "/auth/login/"         # quando tentar acessar algo logado
