# Generated by Django 5.2.10 on 2026-01-13 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpotForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_utc', models.DateTimeField()),
                ('end_utc', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather.spot')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['spot', 'start_utc', 'end_utc'], name='weather_spo_spot_id_194208_idx')],
            },
        ),
    ]
