# Generated by Django 5.2.10 on 2026-01-13 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ('name',), 'verbose_name': 'Spot', 'verbose_name_plural': 'Spots'},
        ),
        migrations.AddField(
            model_name='spot',
            name='city',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='spot',
            name='forecast_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='spot',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='ForecastHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Hora (UTC)')),
                ('wave_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura onda (m)')),
                ('wave_period_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Período onda (s)')),
                ('wave_direction_deg', models.IntegerField(blank=True, null=True, verbose_name='Direção onda (°)')),
                ('swell_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura swell (m)')),
                ('swell_period_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Período swell (s)')),
                ('swell_direction_deg', models.IntegerField(blank=True, null=True, verbose_name='Direção swell (°)')),
                ('wind_speed_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Vento (m/s)')),
                ('wind_direction_deg', models.IntegerField(blank=True, null=True, verbose_name='Direção vento (°)')),
                ('water_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp água (°C)')),
                ('air_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp ar (°C)')),
                ('source', models.CharField(blank=True, max_length=40, null=True, verbose_name='Fonte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='weather.spot', verbose_name='Spot')),
            ],
            options={
                'verbose_name': 'Previsão (hora)',
                'verbose_name_plural': 'Previsões (horas)',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='StormglassRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('request_count', models.IntegerField(blank=True, null=True, verbose_name='RequestCount')),
                ('daily_quota', models.IntegerField(blank=True, null=True, verbose_name='DailyQuota')),
                ('params', models.TextField(blank=True, null=True, verbose_name='Params')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.spot', verbose_name='Spot')),
            ],
            options={
                'verbose_name': 'Log Stormglass',
                'verbose_name_plural': 'Logs Stormglass',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='SpotForecast',
        ),
        migrations.AddConstraint(
            model_name='forecasthour',
            constraint=models.UniqueConstraint(fields=('spot', 'time', 'source'), name='uniq_spot_time_source'),
        ),
    ]
