# Generated by Django 5.2.10 on 2026-01-13 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_spot_options_spot_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecasthour',
            options={'ordering': ['spot', 'time'], 'verbose_name': 'Previsão horária', 'verbose_name_plural': 'Previsões horárias'},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['name'], 'verbose_name': 'Spot de pesca', 'verbose_name_plural': 'Spots de pesca'},
        ),
        migrations.AlterModelOptions(
            name='stormglassrequestlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log Stormglass', 'verbose_name_plural': 'Logs Stormglass'},
        ),
        migrations.RemoveConstraint(
            model_name='forecasthour',
            name='uniq_spot_time_source',
        ),
        migrations.RenameField(
            model_name='stormglassrequestlog',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='city',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='forecast_updated_at',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='state',
        ),
        migrations.RemoveField(
            model_name='stormglassrequestlog',
            name='params',
        ),
        migrations.AddField(
            model_name='forecasthour',
            name='gust_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Rajada (m/s)'),
        ),
        migrations.AddField(
            model_name='spot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='last_forecast_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='air_temp_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp. do ar (°C)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='source',
            field=models.CharField(default='noaa', max_length=30, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_hours', to='weather.spot', verbose_name='Spot'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='swell_direction_deg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Direção do swell (°)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='swell_height_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura do swell (m)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='swell_period_s',
            field=models.FloatField(blank=True, null=True, verbose_name='Período do swell (s)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='water_temp_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp. da água (°C)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='wave_direction_deg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Direção da onda (°)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='wave_height_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura da onda (m)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='wave_period_s',
            field=models.FloatField(blank=True, null=True, verbose_name='Período da onda (s)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='wind_direction_deg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Direção do vento (°)'),
        ),
        migrations.AlterField(
            model_name='forecasthour',
            name='wind_speed_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Vento (m/s)'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stormglassrequestlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stormglassrequestlog',
            name='daily_quota',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quota diária'),
        ),
        migrations.AlterField(
            model_name='stormglassrequestlog',
            name='request_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Requests usados hoje'),
        ),
        migrations.AlterUniqueTogether(
            name='forecasthour',
            unique_together={('spot', 'time')},
        ),
    ]
