# Generated by Django 5.2.10 on 2026-01-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catches/photos/')),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('location', models.CharField(max_length=180)),
                ('caught_at', models.DateTimeField(verbose_name='Horário')),
                ('bait', models.CharField(blank=True, max_length=120, verbose_name='Isca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='members.member', verbose_name='Responsável')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catches', to='catches.species')),
            ],
            options={
                'ordering': ['-caught_at'],
            },
        ),
    ]
