# Generated by Django 5.2.10 on 2026-01-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0001_initial'),
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='species',
            name='fishbase_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AddField(
            model_name='species',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='species',
            name='wikipedia_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='catch',
            name='bait',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='catch',
            name='caught_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='catch',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='catch',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='members.member'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
