# Generated by Django 5.2.10 on 2026-01-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0002_alter_species_options_species_fishbase_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='min_length_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='species',
            name='points_per_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
