# Generated by Django 5.2.10 on 2026-01-12 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0003_species_min_length_cm_species_points_per_cm'),
        ('members', '0003_alter_member_options_member_gender_alter_member_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catch',
            options={'ordering': ['-caught_at'], 'verbose_name': 'Captura', 'verbose_name_plural': 'Capturas'},
        ),
        migrations.AlterField(
            model_name='catch',
            name='bait',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Isca'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='caught_at',
            field=models.DateTimeField(verbose_name='Data da captura'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado em'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Comprimento (cm)'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='members.member', verbose_name='Membro'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='catches/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catches', to='catches.species', verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)'),
        ),
    ]
