# Generated by Django 5.2.10 on 2026-01-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0004_alter_catch_options_alter_catch_bait_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
        migrations.AlterField(
            model_name='catch',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tamanho (cm)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='fishbase_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='FishBase ID'),
        ),
        migrations.AlterField(
            model_name='species',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem (URL)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='min_length_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Comprimento mínimo (cm)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome comum'),
        ),
        migrations.AlterField(
            model_name='species',
            name='points_per_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Pontos por centímetro'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Nome científico'),
        ),
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='species',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='species',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='species',
            name='wikipedia_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título na Wikipedia'),
        ),
    ]
