# Generated by Django 5.2.10 on 2026-01-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0005_alter_species_options_alter_catch_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='behavior',
            field=models.TextField(blank=True, null=True, verbose_name='Comportamento'),
        ),
        migrations.AddField(
            model_name='species',
            name='best_times',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Melhor horário/condição'),
        ),
        migrations.AddField(
            model_name='species',
            name='habitats',
            field=models.TextField(blank=True, null=True, verbose_name='Locais / Habitat'),
        ),
        migrations.CreateModel(
            name='SpeciesBaitIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bait_name', models.CharField(max_length=120, verbose_name='Isca / Técnica')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Dicas')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bait_ideas', to='catches.species', verbose_name='Espécie')),
            ],
            options={
                'verbose_name': 'Isca indicada',
                'verbose_name_plural': 'Iscas indicadas',
                'ordering': ['bait_name'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='species/photos/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=140, null=True, verbose_name='Legenda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catches.species', verbose_name='Espécie')),
            ],
            options={
                'verbose_name': 'Foto da espécie',
                'verbose_name_plural': 'Fotos das espécies',
                'ordering': ['-created_at'],
            },
        ),
    ]
