# Generated by Django 5.2.10 on 2026-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0006_species_behavior_species_best_times_species_habitats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_competition_allowed',
            field=models.BooleanField(default=True, verbose_name='Aceita na competição'),
        ),
    ]
